### ISSUE TITLE
Complete posterior (options) part of Beta

### ISSUE THREAD

**Issue by yamir1995** [Topl/agile#14]
Complete beta-binomial model with posterior (voting distribution) added to prior

**Comment by kcraath** [comment]
Remember your model will output a posterior distribution. There is nothing more to it. You start with a **binomial distribution** (Arbiteurs voting 0 or 1) **+ Beta** (Arbiteurs weight given to their vote) and you end with a **beta distribution** (a distribution between 0 and 1 shifted according to the votes and weights of the arbiteurs). Here is a simple toy example in **R**: 
https://cran.r-project.org/web/packages/TailRank/vignettes/betabinomial.pdf

What I want to see first is this model of yours in action. So getting github + Jupiter(Python) Notebooks set up so I can see the output and I can reply using the R kernel.  Give me a similar presentation to what the above referenced **pdf** looks like. 

What you are referring to in your title of this sprint is the **resolution** of the market. That is after the model has run its course and we are then comparing the results of the model with the truth of the contract outcome. So essentially how someone will get paid for participating in a particular contracts reputation score. 

Here are some references that might help you think through the resolution. 
https://en.wikipedia.org/wiki/Binomial_options_pricing_model
http://www.goddardconsulting.ca/option-pricing-binomial-index.html

**Comment by kcraath** [comment]
Let's have a call later today.
